version: '3.8'

services:
  accounts-db:
    image: postgres:14-bullseye
    container_name: accounts-postgres-db
    ports:
      - "5100:5432"
    environment:
      POSTGRES_DB: accountsdb
      POSTGRES_USER: siya7
      POSTGRES_PASSWORD: Welcome123
    volumes:
      - ./pgdata:/var/lib/postgresql/accounts-data
    networks:
      - accounts-db-network

networks:
  accounts-db-network:
    driver: bridge