spring:
  application:
    name: accounts
  profiles:
    active: "prod"

  datasource:
    url: jdbc:postgresql://localhost:5436/accountsdb
    username: siya7
    password: Welcome231

  jpa:
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyHbmImpl
    properties:
      hibernate:
        format_sql: false
        show_sql: false
        dialect: org.hibernate.dialect.PostgreSQLDialect
  config:
    import: "optional:configserver:http://localhost:8071/"

  cloud:
    openfeign:
      circuitbreaker:
        enabled: true

    function:
      definition: updateCommunication
    stream:
      bindings:
        updateCommunication-in-0:
          destination: communication-sent
          group: ${spring.application.name}
        sendCommunication-out-0:
          destination: send-communication
      kafka:
        binder:
          brokers:
            - localhost:9092

  rabbitmq:
    host: "localhost"
    port: 5672
    username: "guest"
    password: "guest"
    connection-timeout: 10s

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    shutdown:
      enabled: true
    health:
      probes:
        enabled: true

  info:
    env:
      enable: true

  metrics:
    tags:
      application: ${spring.application.name}

endpoints:
  shutdown:
    enabled: true

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

info:
  app:
    name: "accounts"
    description: "Eazy Bank Microservices"
    version: "1.0.0"

logging:
  level:
    com:
      eazybytes:
        accounts: DEBUG
    org.springframework.cloud.stream: DEBUG
    org.springframework.messaging: DEBUG

  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"

  resilience4j.circuitbreaker:
    configs:
      default:
        slidingWindowSize: 10 #how many requests to monitor from CLOSED to OPEN state
        permittedNumberOfCallsInHalfOpenState: 2
        failureRateThreshold: 50
        waitDurationInOpenState: 10000